import clogo from "../assets/c-logo.png";
import reactt from "../assets/react.svg";
import node from "../assets/Nodejs.png";
import Mongo from "../assets/MongoDB.png";
import python from "../assets/python.png";
import Expo from "../assets/expo.png";
import Docker from "../assets/Docker.png";
import Git from "../assets/Git.png";
export const navigation = [
  {
    id: "0",
    title: "Home",
    url: "#Home",
  },
  {
    id: "1",
    title: "About",
    url: "#About",
  },
  {
    id: "2",
    title: "Skills",
    url: "#Skills",
  },
  {
    id: "3",
    title: "Projects",
    url: "#Projects",
  },
  {
    id: "4",
    title: "Contact Me",
    url: "#Contact",
  },
];
export const Mobile = [
  { id: 0 },
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 },
  { id: 10 },
  { id: 11 },
  { id: 12 },
  { id: 13 },
  { id: 14 },
  { id: 15 },
  { id: 16 },
  { id: 17 },
  { id: 18 },
  { id: 19 },
  { id: 20 },
];
export const background = [
  { id: 0 },
  { id: 1 },
  { id: 2 },
  { id: 3 },
  { id: 4 },
  { id: 5 },
  { id: 6 },
  { id: 7 },
  { id: 8 },
  { id: 9 },
  { id: 10 },
  { id: 11 },
  { id: 12 },
  { id: 13 },
  { id: 14 },
  { id: 15 },
  { id: 16 },
  { id: 17 },
  { id: 18 },
  { id: 19 },
  { id: 20 },
  { id: 21 },
  { id: 22 },
  { id: 23 },
  { id: 24 },
  { id: 25 },
  { id: 26 },
  { id: 27 },
  { id: 28 },
  { id: 29 },
  { id: 30 },
  { id: 31 },
  { id: 32 },
  { id: 33 },
  { id: 34 },
  { id: 35 },
  { id: 36 },
  { id: 37 },
  { id: 38 },
  { id: 39 },
  { id: 40 },
  { id: 41 },
  { id: 42 },
  { id: 43 },
  { id: 44 },
  { id: 45 },
];
export const collabContent = [
  {
    id: "0",
    title: "Front-end Tools:",
    text: "React.js-(React Naitive, Next.js) Styling-tailwind css",
  },
  {
    id: "1",
    title: "Back-end Tools:",
    text: "Node.js : Express, Python : Flask",
  },
  {
    id: "2",
    title: "Databases:",
    text: "MongoDB ",
  },
  {
    id: "3",
    title: "IBM Full-Stack Javascript Development Certificate",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "C++",
    icon: clogo,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "React",
    icon: reactt,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "Node",
    icon: node,
    width: 40,
    height: 36,
  },
  {
    id: "3",
    title: "MongoDB",
    icon: Mongo,
    width: 40,
    height: 35,
  },
  {
    id: "4",
    title: "python",
    icon: python,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "Expo",
    icon: Expo,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Docker",
    icon: Docker,
    width: 45,
    height: 45,
  },
  {
    id: "7",
    title: "Github",
    icon: Git,
    width: 38,
    height: 32,
  },
];
